### ISSUE TITLE
Unable to run Quilkin proxy - crashes on startup

### ISSUE THREAD

**Issue by lyyQwQ** [googleforgames/quilkin#1038]
**What happened**:
Quilkin proxy crashes immediately after startup, regardless of installation method (both Docker and Cargo install).

**What you expected to happen**:
Quilkin proxy should start and run normally.

**How to reproduce it (as minimally and precisely as possible)**:
1. Using Docker:
```
docker run -e RUST_BACKTRACE=1 --network host us-docker.pkg.dev/quilkin/ci/quilkin:0.10.0-dev-083d425 proxy --port 28868 --to 127.0.0.1:28869
```

2. Using Cargo installed version:
```
quilkin proxy --port 7777 --to [destination_ip:port]
```

**Anything else we need to know?**:
Both installation methods result in immediate crashes.

**Environment**:
- Quilkin version: 0.10.0-dev (Docker), 0.9.0 (Cargo install)
- Execution environment: Both Docker container and binary (cargo install)
- Operating system: Ubuntu 20.04.6 LTS x86_64
- CPU: AMD EPYC-Milan
- Memory: 461MiB
- Kernel: 5.4.0-200-generic
- Custom filters?: No

**Logs**:

Docker version logs:
```
{"timestamp":"2024-11-14T09:12:49.471366Z","level":"INFO","fields":{"message":"Starting Quilkin","version":"0.10.0-dev","commit":"083d4255081d7525ab660afe1293b47a553fcfc4"},"target":"quilkin::cli","filename":"src/cli.rs","threadId":"ThreadId(1)"}
{"timestamp":"2024-11-14T09:12:49.471551Z","level":"INFO","fields":{"message":"Starting admin endpoint","address":"[::]:8000"},"target":"quilkin::components::admin","filename":"src/components/admin.rs","threadId":"ThreadId(1)"}
{"timestamp":"2024-11-14T09:12:49.471604Z","level":"INFO","fields":{"message":"Starting proxy","port":28868,"proxy_id":"vm1031774.cloudsilk.io"},"target":"quilkin::cli::proxy","filename":"src/cli/proxy.rs","span":{"name":"run"},"spans":[{"name":"run"}],"threadId":"ThreadId(1)"}
{"timestamp":"2024-11-14T09:12:49.471795Z","level":"ERROR","fields":{"message":"Panic has occurred. Moving to Unhealthy","panic_info":"panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/shutdown.rs:51:21:\nCannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context."},"target":"quilkin::components::admin::health","filename":"src/components/admin/health.rs","span":{"name":"run"},"spans":[{"name":"run"}],"threadId":"ThreadId(1)"}
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/shutdown.rs:51:21:
Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.
```

Cargo installed version logs:
```
2024-11-10T06:32:07.472844Z  INFO ThreadId(01) quilkin::cli: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/quilkin-0.9.0/src/cli.rs: Starting Quilkin version="0.9.0"
2024-11-10T06:32:07.472924Z  INFO ThreadId(01) quilkin::components::admin: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/quilkin-0.9.0/src/components/admin.rs: Starting admin endpoint address=[::]:8000
2024-11-10T06:32:07.472991Z  INFO ThreadId(01) run: quilkin::cli::proxy: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/quilkin-0.9.0/src/cli/proxy.rs: Starting proxy port=7777 proxy_id="vm1031774.cloudsilk.io"
2024-11-10T06:32:07.473486Z  INFO ThreadId(07) quilkin::components::proxy::io_uring_shared: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/quilkin-0.9.0/src/components/proxy/io_uring_shared.rs: io-uring loop shutdown requested
2024-11-10T06:32:07.473508Z  INFO ThreadId(01) run: quilkin::components::proxy: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/quilkin-0.9.0/src/components/proxy.rs: Quilkin is ready
2024-11-10T06:32:07.473626Z  INFO ThreadId(02) quilkin::components::proxy::packet_router: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/quilkin-0.9.0/src/components/proxy/packet_router.rs: pipeline reporting task closed
2024-11-10T06:32:07.473733Z  INFO ThreadId(08) quilkin::codec::qcmp: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/quilkin-0.9.0/src/codec/qcmp.rs: QCMP thread was signaled to shutdown
2024-11-10T06:32:07.473800Z  INFO ThreadId(09) quilkin::net::phoenix: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/quilkin-0.9.0/src/net/phoenix.rs: starting phoenix HTTP service addr=[::]:7600
```

**Comment by markmandel** [comment]
Huh weird... how did that pass CI?

**Comment by XAMPPRocky** [comment]
@markmandel I don't think we have integration tests for this path, most of the tests are focused on the more advanced setups.

**Comment by markmandel** [comment]
I would have thought

https://github.com/googleforgames/quilkin/blob/a4f9db1d70c3ab8fea5dda00152fc5c6064b0af6/cloudbuild.yaml#L62-L81

Would have caught this 🤔 (but haven't actually looked at build results yet).

**Comment by thinkong** [comment]
Any update on this? I am getting the same problem

**Comment by lyyQwQ** [comment]
>Any update on this? I am getting the same problem

No, but you can try a higher version of the system. I have another server running Ubuntu 22, and everything is working fine. But I can't use that server to meet my needs.

**Comment by thinkong** [comment]
> > Any update on this? I am getting the same problem
> 
> No, but you can try a higher version of the system. I have another server running Ubuntu 22, and everything is working fine. But I can't use that server to meet my needs.

Oh.. I see.. guess we are going to go back to 0.8.0 for now.. since that seems to be working atm

**Comment by markmandel** [comment]
oooh! That's why it's not picked up in CI, it only happens in older linux versions.

**Comment by lyyQwQ** [comment]
> oooh! That's why it's not picked up in CI, it only happens in older linux versions.

Sorry I forgot to bring up this issue here, because I posted similar messages on Discord beforehand

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I'm going to close this issue as we only support the latest version of Ubuntu

**Comment by marklomas** [comment]
I'm seeing this after having installed Ubuntu 24.04 from scratch on a new system. It works fine on my Ubuntu 22.04 system.

**What happens**

Quilkin proxy crashes on startup.

**What you expect to happen**

Quilkin starts normally, reporting something like this (as it does on Ubuntu 22.04):

```
{"timestamp":"2025-03-26T21:18:45.505160Z","level":"INFO","fields":{"message":"Starting Quilkin","version":"0.9.0","commit":"b62ba024a0c7e5bc27eda6c2b785705ffe3d64bb"},"target":"quilkin::cli","filename":"src/cli.rs","threadId":"ThreadId(1)"}
{"timestamp":"2025-03-26T21:18:45.505848Z","level":"INFO","fields":{"message":"Starting admin endpoint","address":"[::]:8000"},"target":"quilkin::components::admin","filename":"src/components/admin.rs","threadId":"ThreadId(1)"}
{"timestamp":"2025-03-26T21:18:45.506316Z","level":"INFO","fields":{"message":"Starting proxy","port":7777,"proxy_id":"7742b58f3214"},"target":"quilkin::cli::proxy","filename":"src/cli/proxy.rs","span":{"name":"run"},"spans":[{"name":"run"}],"threadId":"ThreadId(1)"}
{"timestamp":"2025-03-26T21:18:45.529674Z","level":"INFO","fields":{"message":"Quilkin is ready"},"target":"quilkin::components::proxy","filename":"src/components/proxy.rs","span":{"name":"run"},"spans":[{"name":"run"}],"threadId":"ThreadId(1)"}
{"timestamp":"2025-03-26T21:18:45.530224Z","level":"INFO","fields":{"message":"starting phoenix HTTP service","addr":"[::]:7600"},"target":"quilkin::net::phoenix","filename":"src/net/phoenix.rs","threadId":"ThreadId(44)"}
```

**How to reproduce it**

Exactly as the OP did with this:

```
docker run -e RUST_BACKTRACE=1 --network host us-docker.pkg.dev/quilkin/ci/quilkin:0.10.0-dev-083d425 proxy --port 28868 --to 127.0.0.1:28869
```

or with this:

```
docker run --rm -e RUST_BACKTRACE=1 us-docker.pkg.dev/quilkin/release/quilkin:0.9.0 proxy --to 127.0.0.1:7778
```

**Anything else we need to know**

I installed docker using `sudo apt install docker.io docker-compose-v2`.

**Environment**

```
$ docker version
Client:
 Version:           26.1.3
 API version:       1.45
 Go version:        go1.22.2
 Git commit:        26.1.3-0ubuntu1~24.04.1
 Built:             Mon Oct 14 14:29:26 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          26.1.3
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.22.2
  Git commit:       26.1.3-0ubuntu1~24.04.1
  Built:            Mon Oct 14 14:29:26 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.24
  GitCommit:        
 runc:
  Version:          1.1.12-0ubuntu3.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:
```

```
$ docker info | grep Runtime
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
```

```
$ uname -a
Linux Zen 6.11.0-21-generic #21~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Feb 24 16:52:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ ldd --version
ldd (Ubuntu GLIBC 2.39-0ubuntu8.4) 2.39
```

**Logs (Quilkin 0.10.0-dev-083d425)**

```
Unable to find image 'us-docker.pkg.dev/quilkin/ci/quilkin:0.10.0-dev-083d425' locally
0.10.0-dev-083d425: Pulling from quilkin/ci/quilkin
c6b97f964990: Pull complete 
bfb59b82a9b6: Pull complete 
8ffb3c3cf71a: Pull complete 
a62778643d56: Pull complete 
7c12895b777b: Pull complete 
33e068de2649: Pull complete 
5664b15f108b: Pull complete 
0bab15eea81d: Pull complete 
4aa0ea1413d3: Pull complete 
da7816fa955e: Pull complete 
9aee425378d2: Pull complete 
06e8c7084bea: Pull complete 
f823d6cf5f75: Pull complete 
6f971e93c4e2: Pull complete 
c83c31ce41af: Pull complete 
0cb5c07f8edd: Pull complete 
235b0d55b8e1: Pull complete 
2520628d5c59: Pull complete 
dfc844d5cefa: Pull complete 
Digest: sha256:dc113d39ab1a775ca7c7fb5bfa373841fc34058637662e9db936663891084c5b
Status: Downloaded newer image for us-docker.pkg.dev/quilkin/ci/quilkin:0.10.0-dev-083d425
{"timestamp":"2025-03-26T21:13:28.545140Z","level":"INFO","fields":{"message":"Starting Quilkin","version":"0.10.0-dev","commit":"083d4255081d7525ab660afe1293b47a553fcfc4"},"target":"quilkin::cli","filename":"src/cli.rs","threadId":"ThreadId(1)"}
{"timestamp":"2025-03-26T21:13:28.545442Z","level":"INFO","fields":{"message":"Starting admin endpoint","address":"[::]:8000"},"target":"quilkin::components::admin","filename":"src/components/admin.rs","threadId":"ThreadId(1)"}
{"timestamp":"2025-03-26T21:13:28.545605Z","level":"INFO","fields":{"message":"Starting proxy","port":28868,"proxy_id":"Zen"},"target":"quilkin::cli::proxy","filename":"src/cli/proxy.rs","span":{"name":"run"},"spans":[{"name":"run"}],"threadId":"ThreadId(1)"}
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/shutdown.rs:51:21:
Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.
stack backtrace:
{"timestamp":"2025-03-26T21:13:28.546238Z","level":"ERROR","fields":{"message":"Panic has occurred. Moving to Unhealthy","panic_info":"panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/shutdown.rs:51:21:\nCannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context."},"target":"quilkin::components::admin::health","filename":"src/components/admin/health.rs","span":{"name":"run"},"spans":[{"name":"run"}],"threadId":"ThreadId(1)"}
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: tokio::runtime::blocking::pool::BlockingPool::shutdown
   3: core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>
   4: quilkin::components::proxy::io_uring_shared::IoUringLoop::spawn
   5: quilkin::components::proxy::Proxy::run::{{closure}}
   6: quilkin::cli::proxy::Proxy::run::{{closure}}::{{closure}}
   7: quilkin::cli::Cli::drive::{{closure}}::{{closure}}
   8: quilkin::main::{{closure}}
   9: quilkin::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Logs (Quilkin 0.9.0)**

```
{"timestamp":"2025-03-26T21:25:21.043225Z","level":"INFO","fields":{"message":"Starting Quilkin","version":"0.9.0","commit":"b62ba024a0c7e5bc27eda6c2b785705ffe3d64bb"},"target":"quilkin::cli","filename":"src/cli.rs","threadId":"ThreadId(1)"}
{"timestamp":"2025-03-26T21:25:21.043499Z","level":"INFO","fields":{"message":"Starting admin endpoint","address":"[::]:8000"},"target":"quilkin::components::admin","filename":"src/components/admin.rs","threadId":"ThreadId(1)"}
{"timestamp":"2025-03-26T21:25:21.043729Z","level":"INFO","fields":{"message":"Starting proxy","port":7777,"proxy_id":"f0ac434e0816"},"target":"quilkin::cli::proxy","filename":"src/cli/proxy.rs","span":{"name":"run"},"spans":[{"name":"run"}],"threadId":"ThreadId(1)"}
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/shutdown.rs:51:21:
Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.
stack backtrace:
{"timestamp":"2025-03-26T21:25:21.044588Z","level":"ERROR","fields":{"message":"Panic has occurred. Moving to Unhealthy","panic_info":"panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/shutdown.rs:51:21:\nCannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context."},"target":"quilkin::components::admin::health","filename":"src/components/admin/health.rs","span":{"name":"run"},"spans":[{"name":"run"}],"threadId":"ThreadId(1)"}
   0: rust_begin_unwind
             at ./rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at ./rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/panicking.rs:72:14
   2: tokio::runtime::blocking::shutdown::Receiver::wait
   3: tokio::runtime::blocking::pool::BlockingPool::shutdown
   4: core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>
   5: quilkin::components::proxy::io_uring_shared::IoUringLoop::spawn
   6: quilkin::components::proxy::Proxy::run::{{closure}}
   7: quilkin::cli::proxy::Proxy::run::{{closure}}::{{closure}}
   8: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
   9: quilkin::cli::Cli::drive::{{closure}}::{{closure}}
  10: tokio::runtime::park::CachedParkThread::block_on
  11: tokio::runtime::runtime::Runtime::block_on
  12: quilkin::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
