### ISSUE TITLE
Something broke generating yaml for mdbook

### ISSUE THREAD

**Issue by markmandel** [googleforgames/quilkin#558]
**What happened**:

Not sure when this started, but it's passing CI (which is another issue)

```
2022-08-08 23:19:12 [INFO] (mdbook::book): Book building has started
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', src/main.rs:121:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-08-08 23:20:25 [ERROR] (mdbook::preprocess::links): Error updating "{{#include ../../../target/quilkin.filters.capture.v1alpha1.yaml}}", Could not read file for link {{#include ../../../target/quilkin.filters.capture.v1alpha1.yaml}} (/workspace/docs/src/filters/../../../target/quilkin.filters.capture.v1alpha1.yaml)
2022-08-08 23:20:25 [WARN] (mdbook::preprocess::links): Caused By: No such file or directory (os error 2)
2022-08-08 23:20:25 [ERROR] (mdbook::preprocess::links): Error updating "{{#include ../../../target/quilkin.filters.compress.v1alpha1.yaml}}", Could not read file for link {{#include ../../../target/quilkin.filters.compress.v1alpha1.yaml}} (/workspace/docs/src/filters/../../../target/quilkin.filters.compress.v1alpha1.yaml)
2022-08-08 23:20:25 [WARN] (mdbook::preprocess::links): Caused By: No such file or directory (os error 2)
2022-08-08 23:20:25 [ERROR] (mdbook::preprocess::links): Error updating "{{#include ../../../target/quilkin.filters.concatenate_bytes.v1alpha1.yaml}}", Could not read file for link {{#include ../../../target/quilkin.filters.concatenate_bytes.v1alpha1.yaml}} (/workspace/docs/src/filters/../../../target/quilkin.filters.concatenate_bytes.v1alpha1.yaml)
2022-08-08 23:20:25 [WARN] (mdbook::preprocess::links): Caused By: No such file or directory (os error 2)
2022-08-08 23:20:25 [ERROR] (mdbook::preprocess::links): Error updating "{{#include ../../../target/quilkin.filters.debug.v1alpha1.yaml}}", Could not read file for link {{#include ../../../target/quilkin.filters.debug.v1alpha1.yaml}} (/workspace/docs/src/filters/../../../target/quilkin.filters.debug.v1alpha1.yaml)
2022-08-08 23:20:25 [WARN] (mdbook::preprocess::links): Caused By: No such file or directory (os error 2)
2022-08-08 23:20:25 [ERROR] (mdbook::preprocess::links): Error updating "{{#include ../../../target/quilkin.filters.firewall.v1alpha1.yaml}}", Could not read file for link {{#include ../../../target/quilkin.filters.firewall.v1alpha1.yaml}} (/workspace/docs/src/filters/../../../target/quilkin.filters.firewall.v1alpha1.yaml)
2022-08-08 23:20:25 [WARN] (mdbook::preprocess::links): Caused By: No such file or directory (os error 2)
2022-08-08 23:20:25 [ERROR] (mdbook::preprocess::links): Error updating "{{#include ../../../target/quilkin.filters.load_balancer.v1alpha1.yaml}}", Could not read file for link {{#include ../../../target/quilkin.filters.load_balancer.v1alpha1.yaml}} (/workspace/docs/src/filters/../../../target/quilkin.filters.load_balancer.v1alpha1.yaml)
2022-08-08 23:20:25 [WARN] (mdbook::preprocess::links): Caused By: No such file or directory (os error 2)
2022-08-08 23:20:25 [ERROR] (mdbook::preprocess::links): Error updating "{{#include ../../../target/quilkin.filters.local_rate_limit.v1alpha1.yaml}}", Could not read file for link {{#include ../../../target/quilkin.filters.local_rate_limit.v1alpha1.yaml}} (/workspace/docs/src/filters/../../../target/quilkin.filters.local_rate_limit.v1alpha1.yaml)
2022-08-08 23:20:25 [WARN] (mdbook::preprocess::links): Caused By: No such file or directory (os error 2)
2022-08-08 23:20:25 [ERROR] (mdbook::preprocess::links): Error updating "{{#include ../../../target/quilkin.filters.match.v1alpha1.yaml}}", Could not read file for link {{#include ../../../target/quilkin.filters.match.v1alpha1.yaml}} (/workspace/docs/src/filters/../../../target/quilkin.filters.match.v1alpha1.yaml)
2022-08-08 23:20:25 [WARN] (mdbook::preprocess::links): Caused By: No such file or directory (os error 2)
2022-08-08 23:20:25 [ERROR] (mdbook::preprocess::links): Error updating "{{#include ../../../target/quilkin.filters.token_router.v1alpha1.yaml}}", Could not read file for link {{#include ../../../target/quilkin.filters.token_router.v1alpha1.yaml}} (/workspace/docs/src/filters/../../../target/quilkin.filters.token_router.v1alpha1.yaml)
2022-08-08 23:20:25 [WARN] (mdbook::preprocess::links): Caused By: No such file or directory (os error 2)
2022-08-08 23:20:25 [INFO] (mdbook::book): Running the html backend
htmltest started at 11:20:26 on /tmp/docs
```

I only noticed that it because it was failing when i was testing updates to cloud build on my dev project, but it's passing on CI. Not sure why.

```
2022-08-08 23:32:07 [INFO] (mdbook::book): Book building has started
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', src/main.rs:121:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-08-08 23:33:13 [ERROR] (mdbook::preprocess::links): Error updating "{{#include ../../../target/quilkin.filters.capture.v1alpha1.yaml}}", Could not read file for link {{#include ../../../target/quilkin.filters.capture.v1alpha1.yaml}} (/workspace/docs/src/filters/../../../target/quilkin.filters.capture.v1alpha1.yaml)
2022-08-08 23:33:13 [WARN] (mdbook::preprocess::links): Caused By: No such file or directory (os error 2)
2022-08-08 23:33:13 [ERROR] (mdbook::preprocess::links): Error updating "{{#include ../../../target/quilkin.filters.compress.v1alpha1.yaml}}", Could not read file for link {{#include ../../../target/quilkin.filters.compress.v1alpha1.yaml}} (/workspace/docs/src/filters/../../../target/quilkin.filters.compress.v1alpha1.yaml)
2022-08-08 23:33:13 [WARN] (mdbook::preprocess::links): Caused By: No such file or directory (os error 2)
2022-08-08 23:33:13 [ERROR] (mdbook::preprocess::links): Error updating "{{#include ../../../target/quilkin.filters.concatenate_bytes.v1alpha1.yaml}}", Could not read file for link {{#include ../../../target/quilkin.filters.concatenate_bytes.v1alpha1.yaml}} (/workspace/docs/src/filters/../../../target/quilkin.filters.concatenate_bytes.v1alpha1.yaml)
2022-08-08 23:33:13 [WARN] (mdbook::preprocess::links): Caused By: No such file or directory (os error 2)
2022-08-08 23:33:13 [ERROR] (mdbook::preprocess::links): Error updating "{{#include ../../../target/quilkin.filters.debug.v1alpha1.yaml}}", Could not read file for link {{#include ../../../target/quilkin.filters.debug.v1alpha1.yaml}} (/workspace/docs/src/filters/../../../target/quilkin.filters.debug.v1alpha1.yaml)
2022-08-08 23:33:13 [WARN] (mdbook::preprocess::links): Caused By: No such file or directory (os error 2)
2022-08-08 23:33:13 [ERROR] (mdbook::preprocess::links): Error updating "{{#include ../../../target/quilkin.filters.firewall.v1alpha1.yaml}}", Could not read file for link {{#include ../../../target/quilkin.filters.firewall.v1alpha1.yaml}} (/workspace/docs/src/filters/../../../target/quilkin.filters.firewall.v1alpha1.yaml)
2022-08-08 23:33:13 [WARN] (mdbook::preprocess::links): Caused By: No such file or directory (os error 2)
2022-08-08 23:33:13 [ERROR] (mdbook::preprocess::links): Error updating "{{#include ../../../target/quilkin.filters.load_balancer.v1alpha1.yaml}}", Could not read file for link {{#include ../../../target/quilkin.filters.load_balancer.v1alpha1.yaml}} (/workspace/docs/src/filters/../../../target/quilkin.filters.load_balancer.v1alpha1.yaml)
2022-08-08 23:33:13 [WARN] (mdbook::preprocess::links): Caused By: No such file or directory (os error 2)
2022-08-08 23:33:13 [ERROR] (mdbook::preprocess::links): Error updating "{{#include ../../../target/quilkin.filters.local_rate_limit.v1alpha1.yaml}}", Could not read file for link {{#include ../../../target/quilkin.filters.local_rate_limit.v1alpha1.yaml}} (/workspace/docs/src/filters/../../../target/quilkin.filters.local_rate_limit.v1alpha1.yaml)
2022-08-08 23:33:13 [WARN] (mdbook::preprocess::links): Caused By: No such file or directory (os error 2)
2022-08-08 23:33:13 [ERROR] (mdbook::preprocess::links): Error updating "{{#include ../../../target/quilkin.filters.match.v1alpha1.yaml}}", Could not read file for link {{#include ../../../target/quilkin.filters.match.v1alpha1.yaml}} (/workspace/docs/src/filters/../../../target/quilkin.filters.match.v1alpha1.yaml)
2022-08-08 23:33:13 [WARN] (mdbook::preprocess::links): Caused By: No such file or directory (os error 2)
2022-08-08 23:33:13 [ERROR] (mdbook::preprocess::links): Error updating "{{#include ../../../target/quilkin.filters.token_router.v1alpha1.yaml}}", Could not read file for link {{#include ../../../target/quilkin.filters.token_router.v1alpha1.yaml}} (/workspace/docs/src/filters/../../../target/quilkin.filters.token_router.v1alpha1.yaml)
2022-08-08 23:33:13 [WARN] (mdbook::preprocess::links): Caused By: No such file or directory (os error 2)
2022-08-08 23:33:13 [INFO] (mdbook::book): Running the html backend
htmltest started at 11:33:14 on /tmp/docs
========================================================================
book/filters/load_balancer.html
  target does not exist --- book/filters/load_balancer.html --> ../../api/quilkin/filters/load_balancer/struct.Config.html
book/filters/compress.html
  target does not exist --- book/filters/compress.html --> ../../api/quilkin/filters/compress/struct.Config.html
book/filters/match.html
  target does not exist --- book/filters/match.html --> ../../api/quilkin/filters/match/struct.Config.html
  target does not exist --- book/filters/match.html --> ../../api/quilkin/filters/match/struct.Config.html
book/filters/debug.html
  target does not exist --- book/filters/debug.html --> ../../api/quilkin/filters/debug/struct.Config.html
book/filters/token_router.html
  target does not exist --- book/filters/token_router.html --> ../../api/quilkin/filters/token_router/struct.Config.html
book/filters/concatenate_bytes.html
  target does not exist --- book/filters/concatenate_bytes.html --> ../../api/quilkin/filters/concatenate_bytes/struct.Config.html
book/filters/local_rate_limit.html
  target does not exist --- book/filters/local_rate_limit.html --> ../../api/quilkin/filters/local_rate_limit/struct.Config.html
book/filters/capture.html
  target does not exist --- book/filters/capture.html --> ../../api/quilkin/filters/capture/struct.Config.html
book/filters/firewall.html
  target does not exist --- book/filters/firewall.html --> ../../api/quilkin/filters/firewall/struct.Config.html
book/filters/writing_custom_filters.html
  target does not exist --- book/filters/writing_custom_filters.html --> ../../api/quilkin/runner/fn.run.html
  target does not exist --- book/filters/writing_custom_filters.html --> ../../api/quilkin/filters/trait.FilterFactory.html
book/filters.html
  target does not exist --- book/filters.html --> ../api/quilkin/metadata/enum.Value.html
========================================================================
✘✘✘ failed in 8.90022669s
13 errors in 29 documents
make: *** [Makefile:93: test-docs] Error 1
```

**What you expected to happen**:

1. Have `cargo run -q --manifest-path ../Cargo.toml -- -q generate-config-schema -o ../target` in `preprocessor.sh` to work
2. If this happens, fail CI.

**How to reproduce it (as minimally and precisely as possible)**:

Either:

1. run `mdbook` from `./docs`
2. `make docs` from the `build` directory.

**Anything else we need to know?**:

**Environment**: 
- Quilkin version: dev
- Execution environment (binary, container, etc): N/A
- Operating system: Linux (debian)
- Custom filters? (Yes/No - if so, what do they do?): N/A
- Log(s): See: https://github.com/googleforgames/quilkin/pull/557/checks?check_run_id=7736163567
- Others:

**Comment by markmandel** [comment]
Filed;

* https://github.com/rust-lang/mdBook/issues/1872

Otherwise, it might worth running the `preprocessor.sh` file directly ourselves in the Makefile just to check it works before running the `mdbook` command.
